FITZPATRICK17K_DATASET_DIR=/n/data1/hms/dbmi/manrai/derm/Fitzpatrick17k

# Finetune
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of allergic contact dermatitis, a skin disease" --output_dir="dreambooth-outputs/allergic-contact-dermatitis" --disease_class=allergic-contact-dermatitis --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of basal cell carcinoma, a skin disease" --output_dir="dreambooth-outputs/basal-cell-carcinoma" --disease_class=basal-cell-carcinoma --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of folliculitis, a skin disease" --output_dir="dreambooth-outputs/folliculitis" --disease_class=folliculitis --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of lichen planus, a skin disease" --output_dir="dreambooth-outputs/lichen-planus" --disease_class=lichen-planus --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of lupus erythematosus, a skin disease" --output_dir="dreambooth-outputs/lupus-erythematosus" --disease_class=lupus-erythematosus --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of neutrophilic dermatoses, a skin disease" --output_dir="dreambooth-outputs/neutrophilic-dermatoses" --disease_class=neutrophilic-dermatoses --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of photodermatoses, a skin disease" --output_dir="dreambooth-outputs/photodermatoses" --disease_class=photodermatoses --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of psoriasis, a skin disease" --output_dir="dreambooth-outputs/psoriasis" --disease_class=psoriasis --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of sarcoidosis, a skin disease" --output_dir="dreambooth-outputs/sarcoidosis" --disease_class=sarcoidosis --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of squamous cell carcinoma, a skin disease" --output_dir="dreambooth-outputs/squamous-cell-carcinoma" --disease_class=squamous-cell-carcinoma --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of allergic contact dermatitis, a skin disease" --output_dir="dreambooth-inpaint-outputs/allergic-contact-dermatitis" --disease_class=allergic-contact-dermatitis --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of basal cell carcinoma, a skin disease" --output_dir="dreambooth-inpaint-outputs/basal-cell-carcinoma" --disease_class=basal-cell-carcinoma --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of folliculitis, a skin disease" --output_dir="dreambooth-inpaint-outputs/folliculitis" --disease_class=folliculitis --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of lichen planus, a skin disease" --output_dir="dreambooth-inpaint-outputs/lichen-planus" --disease_class=lichen-planus --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of lupus erythematosus, a skin disease" --output_dir="dreambooth-inpaint-outputs/lupus-erythematosus" --disease_class=lupus-erythematosus --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of neutrophilic dermatoses, a skin disease" --output_dir="dreambooth-inpaint-outputs/neutrophilic-dermatoses" --disease_class=neutrophilic-dermatoses --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of photodermatoses, a skin disease" --output_dir="dreambooth-inpaint-outputs/photodermatoses" --disease_class=photodermatoses --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of psoriasis, a skin disease" --output_dir="dreambooth-inpaint-outputs/psoriasis" --disease_class=psoriasis --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of sarcoidosis, a skin disease" --output_dir="dreambooth-inpaint-outputs/sarcoidosis" --disease_class=sarcoidosis --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"
python train_dreambooth_inpaint.py --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_data_dir=/home/lukemelas/data/Fitzpatrick17k --instance_prompt="An image of {}, a skin disease" --validation_prompt="An image of squamous cell carcinoma, a skin disease" --output_dir="dreambooth-inpaint-outputs/squamous-cell-carcinoma" --disease_class=squamous-cell-carcinoma --resolution=512 --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=5e-06 --lr_scheduler="constant" --lr_warmup_steps=0 --num_train_epochs=4 --report_to="wandb"

# Sample from finetuned models
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/allergic-contact-dermatitis --instance_prompt="An image of {}, a skin disease" --disease_class=allergic-contact-dermatitis
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/basal-cell-carcinoma --instance_prompt="An image of {}, a skin disease" --disease_class=basal-cell-carcinoma
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/folliculitis --instance_prompt="An image of {}, a skin disease" --disease_class=folliculitis
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/lichen-planus --instance_prompt="An image of {}, a skin disease" --disease_class=lichen-planus
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/lupus-erythematosus --instance_prompt="An image of {}, a skin disease" --disease_class=lupus-erythematosus
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/neutrophilic-dermatoses --instance_prompt="An image of {}, a skin disease" --disease_class=neutrophilic-dermatoses
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/photodermatoses --instance_prompt="An image of {}, a skin disease" --disease_class=photodermatoses
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/psoriasis --instance_prompt="An image of {}, a skin disease" --disease_class=psoriasis
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/sarcoidosis --instance_prompt="An image of {}, a skin disease" --disease_class=sarcoidosis
python generate.py --model_type "text-to-image" --pretrained_model_name_or_path=dreambooth-outputs/squamous-cell-carcinoma --instance_prompt="An image of {}, a skin disease" --disease_class=squamous-cell-carcinoma
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/allergic-contact-dermatitis --instance_prompt="An image of {}, a skin disease" --disease_class=allergic-contact-dermatitis
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/basal-cell-carcinoma --instance_prompt="An image of {}, a skin disease" --disease_class=basal-cell-carcinoma
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/folliculitis --instance_prompt="An image of {}, a skin disease" --disease_class=folliculitis
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/lichen-planus --instance_prompt="An image of {}, a skin disease" --disease_class=lichen-planus
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/lupus-erythematosus --instance_prompt="An image of {}, a skin disease" --disease_class=lupus-erythematosus
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/neutrophilic-dermatoses --instance_prompt="An image of {}, a skin disease" --disease_class=neutrophilic-dermatoses
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/photodermatoses --instance_prompt="An image of {}, a skin disease" --disease_class=photodermatoses
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/psoriasis --instance_prompt="An image of {}, a skin disease" --disease_class=psoriasis
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/sarcoidosis --instance_prompt="An image of {}, a skin disease" --disease_class=sarcoidosis
python generate.py --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path=dreambooth-inpaint-outputs/squamous-cell-carcinoma --instance_prompt="An image of {}, a skin disease" --disease_class=squamous-cell-carcinoma

# Sample from pretrained models
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=allergic-contact-dermatitis
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=basal-cell-carcinoma
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=folliculitis
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=lichen-planus
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=lupus-erythematosus
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=neutrophilic-dermatoses
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=photodermatoses
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=psoriasis
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=sarcoidosis
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "text-to-image" --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --instance_prompt="An image of {}, a skin disease" --disease_class=squamous-cell-carcinoma
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=allergic-contact-dermatitis
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=basal-cell-carcinoma
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=folliculitis
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=lichen-planus
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=lupus-erythematosus
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=neutrophilic-dermatoses
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=photodermatoses
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=psoriasis
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=sarcoidosis
python generate.py --output_root generations-pretrained --instance_data_dir=${FITZPATRICK17K_DATASET_DIR} --model_type "inpaint" --pretrained_model_name_or_path="runwayml/stable-diffusion-inpainting" --instance_prompt="An image of {}, a skin disease" --disease_class=squamous-cell-carcinoma
